version: '3.8'

networks:
  red1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  db:
    build:
      context: ./db
    networks:
      red1:
        ipv4_address: 172.18.0.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./api
    networks:
      - red1
    restart: always
    depends_on:
      - db
    ports:
      - "5001:5001"

  front:
    build:
      context: ./front
    restart: always  
    depends_on:
      - db
      - backend
    ports:
      - "5173:5173"

volumes:
  db_data:
